# Generated by Django 3.2.9 on 2021-11-20 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('indeks', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('rok_wydania', models.IntegerField()),
                ('wydawnictwo', models.CharField(max_length=200)),
                ('posiadacz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
